#!/usr/bin/env bash
echo "pre commit hook start"

PHP_CS_FIXER="./vendor/bin/php-cs-fixer"
PHP_CS_CONFIG=".php-cs-fixer.dist.php"
PHP_STAN="./vendor/bin/phpstan"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    echo "php-cs-fixer start"
    $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
    echo "php-cs-fixer finish"

    echo "php-stan start"

    if $PHP_STAN analyse -c ./phpstan.neon --memory-limit=512M $CHANGED_FILES; then
      echo 'php-stan finish'
    else
      echo 'php-stan found some errors'
      exit 1;
    fi

    git add $CHANGED_FILES;
fi

echo "pre commit hook finish"
